"""The tool panel an agent is offered — compiled, not written.

Built from the runtime's own declaration (``runtime/schema/tools.json``, produced
by ``ash-runtime --dump-schema``) plus a manifest saying what to offer and how.
See docs/TOOL_PANEL.md for the model and the rules.

The panel used to be a hand-written literal -- 261 lines of it -- and had drifted
from the runtime on four of seven tools. The worst was ``web_fetch(max_length=…)``,
a parameter the runtime dropped: asking for it returned unbounded output with no
error, so the model believed it had a limit it did not have. Compiling means that
disagreement is a startup failure instead.

This lives in the execution plane because **both** consumers need it:

- an agent loop asks for ``format="openai"`` / ``"anthropic"`` and gets
  function-calling schemas;
- the MCP proxy asks for ``format="raw"`` and gets ``{name, description,
  inputSchema}`` -- which is exactly MCP's shape, so no conversion is involved.

It used to live in ``swebench/agent/tools.py``, which meant the proxy could not use
it and hand-wrote its tool list instead: four tools with no check against the
runtime at all. ``swebench.agent.tools`` re-exports these names, and keeps the
parts that genuinely belong to it (``build_panel`` and manifest-defined custom
tools, which reach into that package's registry).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

from ash_sandbox.panel import compile_panel, load_declaration, parse_agent_tool

_REPO = Path(__file__).resolve().parents[2]

#: The runtime declaration a panel is compiled against. Checked in, generated by
#: `ash-runtime --dump-schema` -- so compiling needs no sandbox, and a runtime
#: change that is not regenerated here fails a test rather than reaching a model.
RUNTIME_SCHEMA = _REPO / "runtime" / "schema" / "tools.json"

#: Where a bare panel name (rather than a path) is looked up.
PANEL_DIR = _REPO / "harness" / "tool_panels"

#: What a caller gets without asking: a shell and a file editor. Enough to read,
#: write and modify files and to run commands, which is the whole job for most
#: tasks; anything more is a manifest away.
DEFAULT_PANEL = "default"


def resolve_panel(name_or_path: str) -> Path:
    """A panel name or path as a manifest path.

    A bare name is looked up in ``harness/tool_panels``, and anything with a
    separator or suffix is taken as a path -- which is how a caller supplies their
    own panel without adding it to this repo.
    """
    candidate = Path(name_or_path)
    if candidate.suffix or len(candidate.parts) > 1:
        if not candidate.is_file():
            raise ValueError("no tool panel at %s" % candidate)
        return candidate
    for suffix in (".yaml", ".yml", ".json"):
        shipped = PANEL_DIR / ("%s%s" % (name_or_path, suffix))
        if shipped.is_file():
            return shipped
    available = sorted(p.stem for p in PANEL_DIR.glob("*.y*ml"))
    raise ValueError(
        "unknown tool panel %r; shipped panels are %s, or give a path to your own"
        % (name_or_path, ", ".join(available)))


def read_manifest(path: Path) -> dict:
    text = Path(path).read_text()
    if Path(path).suffix == ".json":
        return json.loads(text)
    import yaml

    return yaml.safe_load(text)


@dataclass(frozen=True)
class ToolPanel:
    """One panel: the schema the model sees and the views that route its calls.

    Both come from one manifest and travel together. Keeping them apart is how the
    routing table and the schema came to disagree.
    """

    schema: List[dict]
    views: Dict[str, Any]              # model-facing name -> AgentToolSpec
    registry: Optional[Any] = None     # ToolRegistry; None = no custom tools

    def names(self) -> List[str]:
        return [spec["name"] if isinstance(spec, dict) else spec.name
                for spec in self.views.values()]

    def is_custom_tool(self, name: str) -> bool:
        """Whether this panel dispatches ``name`` as a manifest-defined binary.

        Asked before routing: a custom tool is expanded into artifact+shell by the
        session executor rather than mapped onto a runtime tool. Answered from this
        panel's own registry, so a caller and its session cannot disagree about
        what is custom -- they hold the same one.
        """
        if self.registry is None:
            return False
        return bool(self.registry.is_custom_tool(name))

    def route(self, name: str, args: dict) -> "tuple[str, dict]":
        """Translate an agent-facing call into a runtime call.

        Route before handing a call to an executor, so interceptors always see the
        runtime tool: one keyed on `shell` must not go blind because a view renamed
        it. An argument the view does not offer raises -- dropping it would leave
        the model believing a setting took effect.
        """
        view = self.views.get(name)
        if view is None:
            raise KeyError("unknown agent tool: %s" % name)
        return view.route(args)


def load_panel(name_or_path: str = DEFAULT_PANEL,
               format: str = "openai",
               registry: Optional[Any] = None) -> ToolPanel:
    """Compile a panel manifest against the checked-in runtime declaration.

    Raises on any disagreement. Falling back to something stale is how the
    hand-written panel drifted for months without anyone noticing.

    ``format="raw"`` yields MCP's ``inputSchema`` shape, which is what the proxy
    serves; the function-calling formats are for an agent loop.
    """
    manifest = read_manifest(resolve_panel(name_or_path))
    specs = [parse_agent_tool(t) for t in manifest["agent_tools"]]
    schema = compile_panel(specs, load_declaration(RUNTIME_SCHEMA), format)
    return ToolPanel(schema=schema, views={s.name: s for s in specs},
                     registry=registry)
