"""The panel is compiled from the runtime's declaration (docs/TOOL_PANEL.md).

The panel used to be a hand-written literal and had drifted from the runtime on four
of seven tools. Worst case: `web_fetch` offered `max_length`, a parameter the runtime
dropped, so the model could ask for a bound, get `isError: false`, and not be
bounded. These tests cover the mechanism that makes that impossible to reintroduce.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "sdk"))

from ash_sandbox.panel import (  # noqa: E402
    AgentToolSpec,
    PanelError,
    compile_panel,
    load_declaration,
    parse_agent_tool,
)

from harness.execution.panel import (  # noqa: E402
    PANEL_DIR,
    RUNTIME_SCHEMA,
    load_panel,
    resolve_panel,
)

DECL = load_declaration(RUNTIME_SCHEMA)




# --------------------------------------------------------------------------- #
#  The checked-in declaration must match the runtime that produced it
# --------------------------------------------------------------------------- #

def _runtime_binary() -> "str | None":
    import shutil

    found = shutil.which("ash-runtime")
    if found:
        return found
    root = Path(__file__).resolve().parents[2]
    for candidate in (root / "runtime" / "ash-runtime", Path("/tmp/ash-rt2"),
                      Path("/tmp/ash-rt")):
        if candidate.is_file():
            return str(candidate)
    return None


def test_the_checked_in_declaration_matches_the_runtime():
    """`runtime/schema/tools.json` is generated by `ash-runtime --dump-schema`. A
    runtime change that is not regenerated here has to fail a test rather than reach
    a model: that stale-copy failure mode is exactly what the compiler replaced."""
    binary = _runtime_binary()
    if binary is None:
        pytest.skip("no ash-runtime binary; run `cd runtime && go build -o ash-runtime .`")
    fresh = json.loads(subprocess.run([binary, "--dump-schema"], capture_output=True,
                                      text=True, timeout=60).stdout)
    stored = json.loads(RUNTIME_SCHEMA.read_text())
    assert fresh == stored, (
        "runtime/schema/tools.json is stale; regenerate with "
        "`./ash-runtime --dump-schema > runtime/schema/tools.json`")


# --------------------------------------------------------------------------- #
#  What the compiler refuses
# --------------------------------------------------------------------------- #

def _spec(**kw) -> AgentToolSpec:
    base = {"name": "shell", "arguments": ["command"]}
    base.update(kw)
    return parse_agent_tool(base)


def test_a_parameter_the_runtime_does_not_accept_is_refused():
    """The `max_length` defect. The runtime ignores an unknown argument silently, so
    the model would believe it took effect."""
    with pytest.raises(PanelError) as caught:
        compile_panel([_spec(name="web_fetch", runtime_tool="web_fetch",
                             arguments=["url", "max_length"])], DECL)
    assert "max_length" in str(caught.value)


def test_a_view_of_a_tool_the_runtime_does_not_serve_is_refused():
    with pytest.raises(PanelError) as caught:
        compile_panel([_spec(name="run_tests", runtime_tool="pytest")], DECL)
    assert "pytest" in str(caught.value)


def test_a_view_without_arguments_is_refused():
    """`arguments` is the parameter surface; omitting it is not "offer everything"."""
    with pytest.raises(PanelError) as caught:
        compile_panel([parse_agent_tool({"name": "shell"})], DECL)
    assert "arguments" in str(caught.value)


def test_a_view_must_offer_what_the_runtime_requires():
    """Withholding a required parameter makes every call fail, so it is refused at
    compile time rather than on the model's first attempt."""
    with pytest.raises(PanelError) as caught:
        compile_panel([_spec(name="text_editor", runtime_tool="text_editor",
                             arguments=["command"])], DECL)   # `path` is required
    assert "path" in str(caught.value)


def test_two_views_may_not_share_a_name():
    with pytest.raises(PanelError):
        compile_panel([_spec(), _spec()], DECL)


def test_provider_hostile_schema_keys_are_stripped():
    """`shell.env` is declared with additionalProperties; some providers reject it,
    and the hand-written panel dropped it silently. Now it is dropped on purpose."""
    panel = load_panel("full").schema
    env = next(t["function"] for t in panel
               if t["function"]["name"] == "shell")["parameters"]["properties"]["env"]
    assert "additionalProperties" not in env
    assert env["type"] == "object", "stripping must not lose the type"


# --------------------------------------------------------------------------- #
#  Renaming and argument mapping
# --------------------------------------------------------------------------- #

def test_a_view_can_rename_the_tool_and_its_arguments():
    panel = compile_panel([parse_agent_tool({
        "name": "run", "runtime_tool": "shell", "description": "run something",
        "arguments": {"cmd": "command"}, "required": ["cmd"]})], DECL)
    fn = panel[0]["function"]
    assert fn["name"] == "run"
    assert set(fn["parameters"]["properties"]) == {"cmd"}
    assert fn["description"] == "run something"


def test_a_rename_onto_a_nonexistent_argument_is_refused():
    with pytest.raises(PanelError) as caught:
        compile_panel([parse_agent_tool({
            "name": "run", "runtime_tool": "shell",
            "arguments": {"cmd": "cmdline"}})], DECL)
    assert "cmdline" in str(caught.value)


# --------------------------------------------------------------------------- #
#  Routing comes from the same views
# --------------------------------------------------------------------------- #

def test_an_argument_the_view_does_not_offer_is_an_error_not_a_drop():
    """Dropping it would leave the model believing a setting took effect, which is the
    `max_length` defect this whole mechanism exists to stop. An earlier version of the
    routing did exactly that, and a test pinned the behaviour in place."""
    panel = load_panel("bash_only")
    with pytest.raises(ValueError) as caught:
        panel.route("shell", {"command": "ls", "max_output_bytes": 20000})
    assert "max_output_bytes" in str(caught.value)
    assert "command" in str(caught.value), "the error should say what is accepted"


def test_each_panel_routes_through_its_own_views():
    """Both panels define `shell` with different parameters. Routing used to resolve
    against a process-wide active panel, so two agents in one process could not have
    different ones -- and batch mode is two agents in one process."""
    default, bash_only = load_panel("default"), load_panel("bash_only")
    assert default.route("shell", {"command": "ls", "tail": 5}) == \
        ("shell", {"command": "ls", "tail": 5})
    with pytest.raises(ValueError):
        bash_only.route("shell", {"command": "ls", "tail": 5})


def test_an_unknown_tool_is_rejected_before_the_runtime():
    with pytest.raises(KeyError):
        load_panel("default").route("no_such_tool", {})


def test_bash_is_gone_as_a_tool_name():
    """bash_only mode offers a view named `shell`. The old `bash` name existed only
    to be mapped back onto `shell`, which is why the route table existed."""
    for name in ("default", "bash_only"):
        panel = load_panel(name)
        assert "bash" not in panel.views
        assert "bash" not in [t["function"]["name"] for t in panel.schema]


def test_bash_only_offers_exactly_one_tool_with_one_parameter():
    panel = load_panel("bash_only")
    assert [t["function"]["name"] for t in panel.schema] == ["shell"]
    params = panel.schema[0]["function"]["parameters"]
    assert set(params["properties"]) == {"command"}
    assert params["required"] == ["command"]


# --------------------------------------------------------------------------- #
#  The shipped panels
# --------------------------------------------------------------------------- #

def test_every_shipped_panel_compiles():
    """A manifest that disagrees with the runtime must fail here, not at run time."""
    shipped = sorted(p.stem for p in PANEL_DIR.glob("*.y*ml"))
    assert shipped, "no panels shipped"
    for name in shipped:
        assert load_panel(name).schema, f"{name} compiled to an empty panel"



def test_reserved_names_are_real_tools_or_documented_aliases():
    """A stale entry would forbid a name for no reason. `bash` is kept on purpose:
    it was the one real alias in the old route table and is still a name a caller
    might map, so a custom tool should not take it."""
    from ash_sandbox import ToolRegistry

    served = {t["name"] for t in json.loads(RUNTIME_SCHEMA.read_text())["tools"]}
    unexplained = ToolRegistry.RESERVED_NAMES - served - {"bash"}
    assert not unexplained, f"{sorted(unexplained)} is reserved but is not a tool"


# --------------------------------------------------------------------------- #
#  A panel is a file
# --------------------------------------------------------------------------- #

def test_a_bare_name_resolves_to_a_shipped_panel():
    """`tools: bash_only` keeps working; it was an enum of two values before."""
    assert resolve_panel("bash_only") == PANEL_DIR / "bash_only.yaml"


def test_a_path_resolves_to_that_file(tmp_path):
    """How a caller ships their own panel without adding it to this repo."""
    mine = tmp_path / "mine.yaml"
    mine.write_text("agent_tools:\n  - name: shell\n    arguments: [command]\n")
    assert resolve_panel(str(mine)) == mine
    assert [t["function"]["name"] for t in load_panel(str(mine)).schema] == ["shell"]


def test_an_unknown_name_says_what_is_available():
    with pytest.raises(ValueError) as caught:
        resolve_panel("does_not_exist")
    assert "bash_only" in str(caught.value)


def test_a_missing_path_is_reported_as_such(tmp_path):
    with pytest.raises(ValueError) as caught:
        resolve_panel(str(tmp_path / "nope.yaml"))
    assert "nope.yaml" in str(caught.value)


# --------------------------------------------------------------------------- #
#  Schema and routing travel together
# --------------------------------------------------------------------------- #


# --------------------------------------------------------------------------- #
#  One file for the whole tool surface
# --------------------------------------------------------------------------- #

COMPLETE = """
agent_tools:
  - name: shell
    arguments: [command, tail]
    required: [command]
  - name: run_tests
    runtime_tool: shell
    description: Run the test suite.
    arguments:
      target:
        name: command
        description: A pytest node id, or the whole command.
    required: [target]

custom_tools:
  - name: lint
    description: Lint with ruff
    binary: {path: /usr/bin/ruff}
    parameters:
      target: {type: string, required: true, map: {positional: 0}}
      fix: {type: boolean, map: {flag: "--fix"}}
"""


# --------------------------------------------------------------------------- #
#  Custom tools belong to a session, not to the process
# --------------------------------------------------------------------------- #

def _tool_dir(root, name, binary):
    d = root / name
    d.mkdir()
    (d / f"{name}.yaml").write_text(
        f"name: {name}\ndescription: {name}\nbinary: {{path: {binary}}}\n"
        f"parameters: {{target: {{type: string, map: {{positional: 0}}}}}}\n")
    return str(d)


