#!/usr/bin/env python3
"""Paper-scale cache evaluation over all available rollout pairs.

The online methods never receive workspace digests.  Digests are generated by
independent Docker replay and are used only to audit correctness and to report
the cost/coverage ceiling of a scan-based full-workspace hash baseline.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import hashlib
import importlib
import json
import os
import random
import statistics
import subprocess
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Any

from ash_sandbox import RelaxedChangeIndex
from ash_sandbox.checkpoints import canonical_prefix
from ash_sandbox.relaxed_prefix import project_environment_prefix
from swebench.sandbox import AshSession
from swebench.workspace_state import compute_session_workspace_digest


# Explicit read roots used by the conservative SWE-Marathon shell proof.
# Keeping the protocol constant here makes this evaluator self-contained.
MARATHON_RELAXED_READ_ROOTS = (
    "/app",
    "/dev_tests",
    "/reference",
    "/usr/local/cargo",
    "/root/.cargo",
)


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def atomic_json(path: Path, value: Any) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    tmp.replace(path)


def tool_messages(trajectory: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        message for message in trajectory.get("messages", [])
        if isinstance(message, dict) and message.get("role") == "tool_result"
    ]


def serialized_call(message: dict[str, Any]) -> str:
    return canonical_prefix({
        "tool_name": str(message.get("tool_name") or ""),
        "tool_args": message.get("tool_args") or {},
    })


def exact_hash(messages: list[dict[str, Any]]) -> str:
    payload = canonical_prefix([
        {
            "tool_name": message.get("tool_name"),
            "tool_args": message.get("tool_args") or {},
            "success": bool(message.get("success", True)),
            "content": message.get("content", ""),
        }
        for message in messages
    ])
    return hashlib.sha256(payload.encode()).hexdigest()


def replay_one(repo: Path, row: dict[str, Any], runtime_bin: str) -> dict[str, Any]:
    trajectory = read_json(repo / row["trajectory"])
    calls = tool_messages(trajectory)
    session = AshSession(
        quiet=True,
        backend={"backend": "docker", "docker": {"runtime_bin": runtime_bin}},
        timeout=60,
    )
    result = {**row, "boundaries": []}
    try:
        if not session.create(row["environment_image"]):
            raise RuntimeError(f"could not create sandbox for {row['run_id']}")
        digest_started = time.perf_counter()
        previous_digest = compute_session_workspace_digest(session, workdir="/app")
        result["initial_workspace_digest"] = previous_digest
        result["initial_workspace_digest_ms"] = round(
            (time.perf_counter() - digest_started) * 1000, 3
        )
        executor = session.executor_for(f"paper-replay-{row['run_id']}")
        prefix: list[dict[str, Any]] = []
        for step, message in enumerate(calls, 1):
            tool_name = str(message.get("tool_name") or "")
            tool_args = dict(message.get("tool_args") or {})
            timeout = min(float(tool_args.get("timeout") or 60), 60.0)
            started = time.perf_counter()
            outcome = executor(tool_name, tool_args, timeout=timeout)
            replay_ms = (time.perf_counter() - started) * 1000
            digest_started = time.perf_counter()
            digest = compute_session_workspace_digest(session, workdir="/app")
            digest_ms = (time.perf_counter() - digest_started) * 1000
            prefix.append(message)
            projection = project_environment_prefix(
                prefix,
                allow_safe_shell=True,
                workspace_roots=MARATHON_RELAXED_READ_ROOTS,
            )
            result["boundaries"].append({
                "step": step,
                "recorded_success": bool(message.get("success", True)),
                "replay_success": outcome.success,
                "replay_error": outcome.error if not outcome.success else "",
                "replay_ms": round(replay_ms, 3),
                "workspace_digest_ms": round(digest_ms, 3),
                "workspace_digest": digest,
                "state_changed": digest != previous_digest,
                "exact_hash": exact_hash(prefix),
                "projection_hash": projection.state_hash,
                "serialized_call": serialized_call(message),
            })
            previous_digest = digest
        return result
    finally:
        session.destroy()


def load_tvcache(root: Path) -> tuple[Any, str]:
    package_root = root / "tvcache/server"
    sys.path.insert(0, str(package_root))
    os.environ["CACHE_BUDGET"] = "100000"
    module = importlib.import_module("tvcache.immutable_env_prefix_tree")
    revision = subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
    ).strip()
    return module.ImmutableEnvPrefixTreeCache, revision


def percentile(values: list[float], fraction: float) -> float:
    values = sorted(values)
    return values[min(len(values) - 1, max(0, int(len(values) * fraction)))]


def bootstrap_task_ci(task_values: dict[str, tuple[int, int]]) -> list[float]:
    rng = random.Random(20260904)
    tasks = sorted(task_values)
    samples = []
    for _ in range(10_000):
        chosen = [rng.choice(tasks) for _ in tasks]
        hits = sum(task_values[task][0] for task in chosen)
        queries = sum(task_values[task][1] for task in chosen)
        samples.append(hits / queries if queries else 0.0)
    samples.sort()
    return [samples[250], samples[9750]]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=Path("results/paper-cache-10task/corpus-manifest.json"))
    parser.add_argument("--tvcache-root", type=Path, required=True)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--force-replay", action="store_true")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    manifest_path = args.manifest if args.manifest.is_absolute() else repo / args.manifest
    output = manifest_path.parent
    manifest = read_json(manifest_path)
    replay_path = output / "workspace-replay.json"
    if replay_path.exists() and not args.force_replay:
        replay_rows = read_json(replay_path)["rows"]
    else:
        runtime_bin = str((repo / "runtime/ash-runtime-linux-amd64").resolve())
        with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as pool:
            futures = [pool.submit(replay_one, repo, row, runtime_bin) for row in manifest["rows"]]
            replay_rows = [future.result() for future in concurrent.futures.as_completed(futures)]
        replay_rows.sort(key=lambda row: (row["task"], row["run_id"]))
        atomic_json(replay_path, {"schema_version": 2, "rows": replay_rows})

    trajectories = {row["run_id"]: tool_messages(read_json(repo / row["trajectory"])) for row in replay_rows}
    cache_type, tvcache_revision = load_tvcache(args.tvcache_root.resolve())
    by_task: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in replay_rows:
        by_task[row["task"]].append(row)

    methods = (
        "no_cache", "exact_history", "tvcache_tcg", "full_workspace_hash",
        "ours_structured_only", "ours",
    )
    totals = {
        name: {
            "hits": 0,
            "queries": 0,
            "restore_valid_hits": 0,
            "current_state_equivalent_hits": 0,
            "replay_steps_avoided": 0,
        }
        for name in methods
    }
    task_counts = {name: defaultdict(lambda: [0, 0]) for name in methods}
    timings = defaultdict(list)
    pair_rows = []

    for task, runs in sorted(by_task.items()):
        for source in runs:
            source_messages = trajectories[source["run_id"]]
            source_exact = {row["exact_hash"]: row for row in source["boundaries"]}
            source_workspace = {row["workspace_digest"]: row for row in source["boundaries"]}
            source_by_reference = {
                f"source-{row['step']}": row for row in source["boundaries"]
            }
            source_calls = [row["serialized_call"] for row in source["boundaries"]]

            for query in runs:
                if query["run_id"] == source["run_id"]:
                    continue
                query_messages = trajectories[query["run_id"]]
                tvcache = cache_type()
                for boundary in source["boundaries"]:
                    step = boundary["step"]
                    tvcache.put(task, source_calls[:step], f"source-{step}", values=[None] * step, tool_exec_times=[0.0] * step)
                relaxed = RelaxedChangeIndex(":memory:")
                relaxed_structured = RelaxedChangeIndex(":memory:")
                for boundary in source["boundaries"]:
                    step = boundary["step"]
                    relaxed.register_projection(
                        task_id=task,
                        env_fingerprint=f"lightstage:{task}",
                        messages=source_messages[:step],
                        reference=f"source-{step}",
                        step_id=step,
                        allow_safe_shell=True,
                        workspace_roots=MARATHON_RELAXED_READ_ROOTS,
                    )
                    relaxed_structured.register_projection(
                        task_id=task,
                        env_fingerprint=f"lightstage:{task}",
                        messages=source_messages[:step],
                        reference=f"source-{step}",
                        step_id=step,
                        allow_safe_shell=False,
                        workspace_roots=MARATHON_RELAXED_READ_ROOTS,
                    )

                pair = {"task": task, "source": source["run_id"], "query": query["run_id"], "source_policy": source["policy"], "query_policy": query["policy"], "queries": []}
                query_calls: list[str] = []
                for boundary in query["boundaries"]:
                    step = boundary["step"]
                    query_calls.append(boundary["serialized_call"])

                    started = time.perf_counter_ns()
                    exact = source_exact.get(boundary["exact_hash"])
                    timings["exact_history"].append((time.perf_counter_ns() - started) / 1e6)
                    started = time.perf_counter_ns()
                    tv_hit, tv_ref, tv_history = tvcache.prefix_match(task, query_calls)
                    timings["tvcache_tcg"].append((time.perf_counter_ns() - started) / 1e6)
                    started = time.perf_counter_ns()
                    workspace = source_workspace.get(boundary["workspace_digest"])
                    timings["full_workspace_hash"].append((time.perf_counter_ns() - started) / 1e6)
                    started = time.perf_counter_ns()
                    ours_match = relaxed.lookup_projection(
                        task_id=task,
                        env_fingerprint=f"lightstage:{task}",
                        messages=query_messages[:step],
                        allow_safe_shell=True,
                        workspace_roots=MARATHON_RELAXED_READ_ROOTS,
                    )
                    timings["ours"].append((time.perf_counter_ns() - started) / 1e6)
                    ours = source_by_reference.get(ours_match.reference) if ours_match else None
                    started = time.perf_counter_ns()
                    structured_match = relaxed_structured.lookup_projection(
                        task_id=task,
                        env_fingerprint=f"lightstage:{task}",
                        messages=query_messages[:step],
                        allow_safe_shell=False,
                        workspace_roots=MARATHON_RELAXED_READ_ROOTS,
                    )
                    timings["ours_structured_only"].append(
                        (time.perf_counter_ns() - started) / 1e6
                    )
                    structured = (
                        source_by_reference.get(structured_match.reference)
                        if structured_match else None
                    )

                    tv_source = source_by_reference.get(str(tv_ref)) if tv_hit else None
                    tv_query_prefix = (
                        query["boundaries"][len(tv_history) - 1]
                        if tv_history else None
                    )
                    tv_restore_valid = bool(
                        tv_source and tv_query_prefix
                        and tv_source["workspace_digest"] == tv_query_prefix["workspace_digest"]
                    )
                    tv_current_equivalent = bool(
                        tv_source
                        and tv_source["workspace_digest"] == boundary["workspace_digest"]
                    )
                    hits = {
                        "no_cache": (False, 0, False, False),
                        "exact_history": (exact is not None, step if exact else 0, bool(exact and exact["workspace_digest"] == boundary["workspace_digest"]), bool(exact and exact["workspace_digest"] == boundary["workspace_digest"])),
                        "tvcache_tcg": (bool(tv_hit), len(tv_history or []), tv_restore_valid, tv_current_equivalent),
                        "full_workspace_hash": (workspace is not None, step if workspace else 0, workspace is not None, workspace is not None),
                        "ours_structured_only": (structured is not None, step if structured else 0, bool(structured and structured["workspace_digest"] == boundary["workspace_digest"]), bool(structured and structured["workspace_digest"] == boundary["workspace_digest"])),
                        "ours": (ours is not None, step if ours else 0, bool(ours and ours["workspace_digest"] == boundary["workspace_digest"]), bool(ours and ours["workspace_digest"] == boundary["workspace_digest"])),
                    }
                    for method, (hit, saved, restore_valid, current_equivalent) in hits.items():
                        totals[method]["queries"] += 1
                        task_counts[method][task][1] += 1
                        if hit:
                            totals[method]["hits"] += 1
                            totals[method]["restore_valid_hits"] += int(restore_valid)
                            totals[method]["current_state_equivalent_hits"] += int(current_equivalent)
                            totals[method]["replay_steps_avoided"] += saved
                            task_counts[method][task][0] += 1
                    pair["queries"].append({
                        "step": step,
                        "workspace_reusable": workspace is not None,
                        "hits": {name: value[0] for name, value in hits.items()},
                        "current_state_equivalent": {name: value[3] for name, value in hits.items()},
                        "replay_steps_avoided": {name: value[1] for name, value in hits.items()},
                    })
                relaxed.close()
                relaxed_structured.close()
                pair_rows.append(pair)

    oracle_opportunities = totals["full_workspace_hash"]["hits"]
    aggregate = {}
    for method in methods:
        row = totals[method]
        hits = row["hits"]
        aggregate[method] = {
            **row,
            "hit_rate": hits / row["queries"],
            "restore_precision": row["restore_valid_hits"] / hits if hits else None,
            "recall_of_workspace_reuse": row["current_state_equivalent_hits"] / oracle_opportunities if oracle_opportunities else None,
            "task_bootstrap_95ci": bootstrap_task_ci(task_counts[method]),
            "lookup_median_ms": statistics.median(timings[method]) if timings[method] else None,
            "lookup_p95_ms": percentile(timings[method], 0.95) if timings[method] else None,
        }

    snapshot_keys = {name: 0 for name in methods}
    snapshot_keys["adjacent_workspace_dedup"] = 0
    total_boundaries = 0
    for task, runs in by_task.items():
        total_boundaries += sum(len(run["boundaries"]) for run in runs)
        snapshot_keys["no_cache"] += sum(len(run["boundaries"]) for run in runs)
        snapshot_keys["exact_history"] += len({row["exact_hash"] for run in runs for row in run["boundaries"]})
        snapshot_keys["tvcache_tcg"] += len({tuple(boundary["serialized_call"] for boundary in run["boundaries"][:i]) for run in runs for i in range(1, len(run["boundaries"]) + 1)})
        snapshot_keys["full_workspace_hash"] += len({row["workspace_digest"] for run in runs for row in run["boundaries"]})
        snapshot_keys["ours_structured_only"] += len({
            project_environment_prefix(
                trajectories[run["run_id"]][:row["step"]],
                allow_safe_shell=False,
                workspace_roots=MARATHON_RELAXED_READ_ROOTS,
            ).state_hash
            for run in runs for row in run["boundaries"]
        })
        snapshot_keys["ours"] += len({row["projection_hash"] for run in runs for row in run["boundaries"]})
        for run in runs:
            previous = run["initial_workspace_digest"]
            for boundary in run["boundaries"]:
                if boundary["workspace_digest"] != previous:
                    snapshot_keys["adjacent_workspace_dedup"] += 1
                previous = boundary["workspace_digest"]

    fingerprint_times = [row["workspace_digest_ms"] for run in replay_rows for row in run["boundaries"]]
    mismatches = [
        {"run_id": run["run_id"], "step": row["step"], "recorded": row["recorded_success"], "replayed": row["replay_success"], "error": row["replay_error"]}
        for run in replay_rows for row in run["boundaries"]
        if row["recorded_success"] != row["replay_success"]
    ]
    result = {
        "schema_version": 2,
        "protocol": {
            "tasks": len(by_task),
            "rollouts": len(replay_rows),
            "recorded_boundaries": total_boundaries,
            "ordered_pairs": len(pair_rows),
            "pair_queries": totals["no_cache"]["queries"],
            "tvcache_repository": "https://github.com/TVCache/TVCache",
            "tvcache_revision": tvcache_revision,
        },
        "aggregate": aggregate,
        "storage": {
            method: {"snapshots": count, "reduction": 1 - count / total_boundaries}
            for method, count in snapshot_keys.items()
        },
        "workspace_fingerprint": {
            "samples": len(fingerprint_times),
            "median_ms": statistics.median(fingerprint_times),
            "p95_ms": percentile(fingerprint_times, 0.95),
        },
        "replay_outcome_mismatches": mismatches,
        "pairs": pair_rows,
    }
    atomic_json(output / "main-results.json", result)
    print(json.dumps({"protocol": result["protocol"], "aggregate": aggregate, "storage": result["storage"], "mismatches": len(mismatches)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
