# =============================================================================
# Ash Infrastructure - Local (Minikube) Configuration
# =============================================================================
# Usage:
#   minikube kubectl -- apply -f rbac.yaml
#   minikube kubectl -- apply -f infra-local.yaml
# =============================================================================

# -----------------------------------------------------------------------------
# Redis - State Store
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ash
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ash
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          args:
            - "redis-server"
            - "--appendonly"
            - "yes"
            - "--protected-mode"
            - "no"
            - "--maxmemory"
            - "256mb"
            - "--maxmemory-policy"
            - "allkeys-lru"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 2
            periodSeconds: 5
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
---

# -----------------------------------------------------------------------------
# Control Plane - Sandbox Lifecycle Manager
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
  namespace: ash
  labels:
    app: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-plane
  template:
    metadata:
      labels:
        app: control-plane
    spec:
      serviceAccountName: control-plane
      nodeSelector:
        kubernetes.io/os: linux
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z redis.ash.svc.cluster.local 6379; do
                echo "Waiting for Redis..."
                sleep 2
              done
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
      containers:
        - name: control-plane
          image: timemagic/ash:control-plane-0.1
          imagePullPolicy: Always
          env:
            - name: TARGET_NAMESPACE
              value: "ash"
            - name: REDIS_HOST
              value: "redis.ash.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: control-plane
  namespace: ash
  labels:
    app: control-plane
spec:
  type: NodePort
  selector:
    app: control-plane
  ports:
    - port: 80
      targetPort: 8080
---

# -----------------------------------------------------------------------------
# Gateway - Request Router / Reverse Proxy
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ash
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z redis.ash.svc.cluster.local 6379; do
                echo "Waiting for Redis..."
                sleep 2
              done
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
      containers:
        - name: gateway
          image: timemagic/ash:gateway-0.1
          imagePullPolicy: Always
          env:
            - name: REDIS_ADDR
              value: "redis.ash.svc.cluster.local:6379"
            - name: REDIS_DB
              value: "0"
            - name: REQUEST_TIMEOUT
              value: "5m"
            - name: READ_TIMEOUT
              value: "6m"
            - name: WRITE_TIMEOUT
              value: "6m"
            - name: IDLE_TIMEOUT
              value: "5m"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ash
  labels:
    app: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 8080
