package ddgs

// Parity tests: assert 1:1 behavior against golden vectors generated by the
// official Python ddgs (v9.14.4) via /tmp/gen_golden.py into
// testdata/parity_golden.json. Covers normalizers, vqd extraction,
// SimpleFilterRanker ordering, and ResultsAggregator dedup/frequency.
// User instruction: "做一套测试，确认ddgs 和我们的是1:1 parity".

import (
	"encoding/json"
	"os"
	"testing"
)

type parityGolden struct {
	NormalizeText []struct {
		In  string `json:"in"`
		Out string `json:"out"`
	} `json:"normalize_text"`
	NormalizeURL []struct {
		In  string `json:"in"`
		Out string `json:"out"`
	} `json:"normalize_url"`
	NormalizeDate []struct {
		In  any    `json:"in"`
		Int bool   `json:"int"`
		Out string `json:"out"`
	} `json:"normalize_date"`
	ExtractVQD []struct {
		In  string `json:"in"`
		Out string `json:"out"`
		Err bool   `json:"err"`
	} `json:"extract_vqd"`
	Ranker []struct {
		Query string              `json:"query"`
		Docs  []map[string]string `json:"docs"`
		Order []string            `json:"order"`
	} `json:"ranker"`
	Aggregator struct {
		Input  []map[string]string `json:"input"`
		Output []map[string]any    `json:"output"`
	} `json:"aggregator"`
}

func loadGolden(t *testing.T) *parityGolden {
	t.Helper()
	data, err := os.ReadFile("testdata/parity_golden.json")
	if err != nil {
		t.Skipf("golden vectors not present: %v", err)
	}
	var g parityGolden
	if err := json.Unmarshal(data, &g); err != nil {
		t.Fatalf("parsing golden vectors: %v", err)
	}
	return &g
}

func TestParityNormalizeText(t *testing.T) {
	g := loadGolden(t)
	for i, c := range g.NormalizeText {
		if got := normalizeText(c.In); got != c.Out {
			t.Errorf("case %d: normalizeText(%q) = %q, python = %q", i, c.In, got, c.Out)
		}
	}
}

func TestParityNormalizeURL(t *testing.T) {
	g := loadGolden(t)
	for i, c := range g.NormalizeURL {
		if got := normalizeURL(c.In); got != c.Out {
			t.Errorf("case %d: normalizeURL(%q) = %q, python = %q", i, c.In, got, c.Out)
		}
	}
}

func TestParityNormalizeDate(t *testing.T) {
	g := loadGolden(t)
	for i, c := range g.NormalizeDate {
		var in any = c.In
		if c.Int {
			// JSON numbers decode as float64; Python got ints.
			in = int64(c.In.(float64))
		}
		if got := normalizeDate(in); got != c.Out {
			t.Errorf("case %d: normalizeDate(%v) = %q, python = %q", i, c.In, got, c.Out)
		}
	}
}

func TestParityExtractVQD(t *testing.T) {
	g := loadGolden(t)
	for i, c := range g.ExtractVQD {
		got, err := extractVQD([]byte(c.In), "q")
		if (err != nil) != c.Err {
			t.Errorf("case %d: extractVQD(%q) err = %v, python err = %v", i, c.In, err, c.Err)
			continue
		}
		if got != c.Out {
			t.Errorf("case %d: extractVQD(%q) = %q, python = %q", i, c.In, got, c.Out)
		}
	}
}

func TestParityRanker(t *testing.T) {
	g := loadGolden(t)
	for _, c := range g.Ranker {
		docs := make([]Result, len(c.Docs))
		for i, d := range c.Docs {
			r := Result{}
			for k, v := range d {
				r[k] = v
			}
			docs[i] = r
		}
		ranked := (simpleFilterRanker{}).rank(docs, c.Query)
		gotOrder := make([]string, len(ranked))
		for i, r := range ranked {
			gotOrder[i] = r.getString("href")
		}
		if len(gotOrder) != len(c.Order) {
			t.Errorf("query %q: got %d docs, python %d: got=%v want=%v",
				c.Query, len(gotOrder), len(c.Order), gotOrder, c.Order)
			continue
		}
		for i := range c.Order {
			if gotOrder[i] != c.Order[i] {
				t.Errorf("query %q position %d: got %q, python %q\n got=%v\nwant=%v",
					c.Query, i, gotOrder[i], c.Order[i], gotOrder, c.Order)
				break
			}
		}
	}
}

func TestParityAggregator(t *testing.T) {
	g := loadGolden(t)
	agg := newResultsAggregator("text")
	for _, in := range g.Aggregator.Input {
		r := newResult("text")
		r.Set("title", in["title"])
		r.Set("href", in["href"])
		r.Set("body", in["body"])
		agg.append(r)
	}
	out := agg.extract()
	if len(out) != len(g.Aggregator.Output) {
		t.Fatalf("got %d results, python %d", len(out), len(g.Aggregator.Output))
	}
	for i, want := range g.Aggregator.Output {
		for _, field := range []string{"title", "href", "body"} {
			wantV, _ := want[field].(string)
			if got := out[i].getString(field); got != wantV {
				t.Errorf("result %d field %s: got %q, python %q", i, field, got, wantV)
			}
		}
	}
}
