package ddgs

// Engine-level parity tests against Python ddgs v9.14.4 golden data.
// Run by `go test ./...`; exercises the engine factories in registry.go.
// Data schemas:
//   - testdata/parity_payloads.json: {engine: [{case:{query,region,safesearch,
//     timelimit,page}, payload:{k:v}}]} — build_payload() outputs for 3 fixed
//     input cases (vqd stubbed to VQD_SENTINEL).
//   - testdata/fixtures/* + testdata/parity_extract.json: identical raw
//     responses fed to both implementations; extracted dicts must match.
// Generated by /tmp/gen_engine_golden.py.
// User instruction: "那做一套测试，确认ddgs 和我们的是1:1 parity".

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"testing"
	"time"
)

type payloadCase struct {
	Case struct {
		Query      string  `json:"query"`
		Region     string  `json:"region"`
		SafeSearch string  `json:"safesearch"`
		TimeLimit  *string `json:"timelimit"`
		Page       int     `json:"page"`
	} `json:"case"`
	Payload map[string]string `json:"payload"`
	Error   string            `json:"error"`
}

// parityEngineFactories maps golden-file engine names to Go factories.
var parityEngineFactories = map[string]engineFactory{
	"duckduckgo_text":   newDuckduckgoText,
	"duckduckgo_images": newDuckduckgoImages,
	"duckduckgo_news":   newDuckduckgoNews,
	"duckduckgo_videos": newDuckduckgoVideos,
	"google":            newGoogle,
	"brave":             newBrave,
	"mojeek":            newMojeek,
	"yahoo":             newYahoo,
	"yahoo_news":        newYahooNews,
	"bing_news":         newBingNews,
	"bing_images":       newBingImages,
	"annasarchive":      newAnnasArchive,
}

func TestParityBuildPayload(t *testing.T) {
	data, err := os.ReadFile("testdata/parity_payloads.json")
	if err != nil {
		t.Skipf("payload golden not present: %v", err)
	}
	var golden map[string][]payloadCase
	if err := json.Unmarshal(data, &golden); err != nil {
		t.Fatalf("parsing payload golden: %v", err)
	}

	// Stub the vqd network fetch with the same sentinel Python used.
	origVQD := fetchVQD
	fetchVQD = func(context.Context, *httpClient, string) (string, error) {
		return "VQD_SENTINEL", nil
	}
	defer func() { fetchVQD = origVQD }()

	for name, cases := range golden {
		factory, ok := parityEngineFactories[name]
		if !ok {
			t.Errorf("no Go factory for golden engine %q", name)
			continue
		}
		t.Run(name, func(t *testing.T) {
			eng, err := factory("", 5*time.Second, Verify{})
			if err != nil {
				t.Fatalf("factory: %v", err)
			}
			be := eng.(*baseEngine)
			for i, c := range cases {
				if c.Error != "" {
					continue // Python raised; skip
				}
				timelimit := ""
				if c.Case.TimeLimit != nil {
					timelimit = *c.Case.TimeLimit
				}
				got, err := be.buildPayload(context.Background(), searchParams{
					Query:      c.Case.Query,
					Region:     c.Case.Region,
					SafeSearch: c.Case.SafeSearch,
					TimeLimit:  timelimit,
					Page:       c.Case.Page,
					Extra:      map[string]string{},
				})
				if err != nil {
					t.Errorf("case %d: buildPayload error: %v", i, err)
					continue
				}
				if len(got) != len(c.Payload) {
					t.Errorf("case %d: %d payload keys, python %d\n got=%v\nwant=%v",
						i, len(got), len(c.Payload), got, c.Payload)
					continue
				}
				for k, want := range c.Payload {
					if gv, ok := got[k]; !ok || gv != want {
						t.Errorf("case %d key %q: got %q, python %q", i, k, gv, want)
					}
				}
			}
		})
	}
}

// parityCompareResults compares extracted results field-by-field against
// Python dicts. Numeric JSON values are compared via fmt.Sprint.
func parityCompareResults(t *testing.T, name string, got []Result, want []map[string]any) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("%s: extracted %d results, python %d", name, len(got), len(want))
	}
	for i := range want {
		for field, wantV := range want[i] {
			gotV, ok := got[i][field]
			if !ok {
				t.Errorf("%s result %d: missing field %q", name, i, field)
				continue
			}
			if !parityValueEqual(gotV, wantV) {
				t.Errorf("%s result %d field %q:\n got  %v\n want %v", name, i, field, gotV, wantV)
			}
		}
	}
}

func parityValueEqual(got, want any) bool {
	if got == nil || want == nil {
		return got == nil && want == nil
	}
	switch w := want.(type) {
	case string:
		g, ok := got.(string)
		return ok && g == w
	case map[string]any:
		g, ok := got.(map[string]any)
		if !ok || len(g) != len(w) {
			return false
		}
		for k, wv := range w {
			if !parityValueEqual(g[k], wv) {
				return false
			}
		}
		return true
	default:
		return fmt.Sprint(got) == fmt.Sprint(want)
	}
}

func TestParityExtractResults(t *testing.T) {
	data, err := os.ReadFile("testdata/parity_extract.json")
	if err != nil {
		t.Skipf("extract golden not present: %v", err)
	}
	var golden map[string][]map[string]any
	if err := json.Unmarshal(data, &golden); err != nil {
		t.Fatalf("parsing extract golden: %v", err)
	}

	fixtures := map[string]struct {
		file    string
		factory engineFactory
	}{
		"ddg_text":   {"ddg_text.html", newDuckduckgoText},
		"ddg_news":   {"ddg_news.json", newDuckduckgoNews},
		"ddg_videos": {"ddg_videos.json", newDuckduckgoVideos},
	}

	for name, want := range golden {
		fx, ok := fixtures[name]
		if !ok {
			t.Errorf("no fixture mapping for golden %q", name)
			continue
		}
		t.Run(name, func(t *testing.T) {
			raw, err := os.ReadFile("testdata/fixtures/" + fx.file)
			if err != nil {
				t.Skipf("fixture missing: %v", err)
			}
			eng, err := fx.factory("", 5*time.Second, Verify{})
			if err != nil {
				t.Fatalf("factory: %v", err)
			}
			be := eng.(*baseEngine)
			text := string(raw)
			if be.preProcessHTML != nil {
				text = be.preProcessHTML(text)
			}
			var got []Result
			if be.extractResults != nil {
				got, err = be.extractResults(context.Background(), text, searchParams{})
			} else {
				got, err = be.extractByXPath(text)
			}
			if err != nil {
				t.Fatalf("extract: %v", err)
			}
			if be.postExtract != nil {
				got = be.postExtract(got)
			}
			parityCompareResults(t, name, got, want)
		})
	}
}
